language: ruby
dist: trusty

addons:
  chrome: stable
  apt:
    sources:
      - "trusty-media"
    packages:
    - ghostscript
    - graphicsmagick
    - imagemagick
    - libreoffice
    - poppler-utils
    - tesseract-ocr
cache:
  bundler: true

before_install:
  # OpenJPEG 2000 2.x backport PPA
  - sudo add-apt-repository ppa:aacid/openjp2trusty -y
  - sudo apt-get update -q
  - sudo apt-get install libopenjp2-tools -y
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - sudo wget -P /opt/install https://brussels.lib.utah.edu/FITS/fits-1.3.0.zip
  - sudo unzip /opt/install/fits-1.3.0.zip -d /opt/install/fits-1.3.0
  - sudo chmod +x /opt/install/fits-1.3.0/*.sh
  - sudo ln -s /opt/install/fits-1.3.0/fits.sh /usr/local/bin/fits.sh
  - sudo wget -q -O /etc/ImageMagick/policy.xml https://raw.githubusercontent.com/marriott-library/newspaper_works/7052ff3bf58022572870a0720d8c5a705090a833/config/vendor/imagemagick-6-policy.xml

rvm:
  - 2.5.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    #- ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test'
  # Travis should check every minor version in a range of supported versions, because
  # rails does not follow sem-ver conventions, see http://guides.rubyonrails.org/maintenance_policy.html
  # It should be sufficient to test only the latest of the patch versions for a minor version, they
  # should be compatible across patch versions (only bug fixes are released in patch versions).
  matrix:
    - "RAILS_VERSION=5.0.6"
    - "RAILS_VERSION=5.1.4"

services:
  - redis-server
before_script:
- jdk_switcher use oraclejdk8
